{{- if and .Values.enabled .Values.pvcsbackup.enabled -}}
apiVersion: stash.appscode.com/v1beta1
kind: BackupConfiguration
metadata:
  name: {{ include "polylite.fullname" $ }}
spec:
  repository:
    name: {{ include "polylite.fullname" $ }}
  schedule: {{ .Values.pvcsbackup.backup.schedule | quote }}
  target:
    ref:
      apiVersion: apps/v1
      kind: {{ $.Values.deployType }}
      name: {{ include "polylite.fullname" $ }}
    {{- range $pvc := $.Values.pvcs }}
    volumeMounts:
      - name: {{ $pvc.name }}
        mountPath: {{ $pvc.mountPath }}
    paths:
      - {{ $pvc.mountPath }}
    {{ end }}
  {{- with .Values.pvcsbackup.backup.retentionPolicy }}
  retentionPolicy:
    {{- toYaml . | nindent 4 }}
  {{- end -}}
{{ end }}