{{- if and .Values.enabled (eq .Values.deployType "DaemonSet") -}}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "polylite.fullname" . }}
  labels:
    {{- include "polylite.labels" . | nindent 4 }}
spec:
  updateStrategy:
    type: {{ .Values.strategy | quote }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "polylite.selectorLabels" . | nindent 6 }}
  template: {{ include "polylite.template.pod" . | nindent 4 }}
{{ end }}