
{{- $vault := .Values.vault -}}
{{- if and .Values.enabled (and $vault.enabled (eq $vault.template.type "configmap")) -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "polylite.vault.templateName" . }}
  labels:
    {{- include "polylite.labels" . | nindent 4 }}
data:
  {{ $vault.template.fileName }}: |
{{ $vault.template.content | indent 4 }}
{{ end }}
